config/routes.rb
Rails.application.routes.draw do

  get 'bingo_sites/sky_bingo'
  get 'bingo_sites/bet365_bingo'
  get 'bingo_sites/lippy_bingo'
  get 'bingo_sites/glossy_bingo'
  get 'bingo_sites/robin_hood_bingo'
  get 'bingo_sites/coral_bingo'
  get 'bingo_sites/ladbrokes_bingo'
  get 'bingo_sites/sun_bingo'
  get 'bingo_sites/bgo_bingo'
  get 'bingo_sites/paddy_power_bingo'

  get 'sports_sites/betway'
  get 'sports_sites/william_hill'
  get 'sports_sites/_888_sport'
  get 'sports_sites/pinnacle_sports'
  get 'sports_sites/unibet'
  get 'sports_sites/paddy_power'
  get 'sports_sites/betfred'
  get 'sports_sites/bet_victor'
  get 'sports_sites/ladbrokes'
  get 'sports_sites/tipico'

  get 'casino_sites/_888_casino'
  get 'casino_sites/mansion_casino'
  get 'casino_sites/royal_panda'
  get 'casino_sites/_32red'
  get 'casino_sites/grosvenor_casinos'
  get 'casino_sites/casumo'
  get 'casino_sites/leo_vegas'
  get 'casino_sites/betway_casino'
  get 'casino_sites/bet_victor'
  get 'casino_sites/netbet_casino'

  get 'live_casino_sites/_888_casino'
  get 'live_casino_sites/mansion_casino'
  get 'live_casino_sites/casumo'
  get 'live_casino_sites/netbet_casino'
  get 'live_casino_sites/royal_panda'
  get 'live_casino_sites/_32red'
  get 'live_casino_sites/bet_victor'
  get 'live_casino_sites/betway_casino'
  get 'live_casino_sites/grosvenor_casinos'
  get 'live_casino_sites/intercasino'

  get 'slot_sites/play_sunny'
  get 'slot_sites/spin_rider'
  get 'slot_sites/spinit'
  get 'slot_sites/sloty'
  get 'slot_sites/starspins'
  get 'slot_sites/videoslots'
  get 'slot_sites/casimba'
  get 'slot_sites/spin_and_win'
  get 'slot_sites/slot_planet'
  get 'slot_sites/casino_heroes'

  get 'corporate/about'
  get 'corporate/contact'
  get 'corporate/terms'
  get 'corporate/privacy'
  get 'corporate/responsible'
  get 'corporate/sitemap'

  get 'slots/best'
  get 'slots/new'
  get 'slots/all'
  get 'slots/rules'

  get 'live_casino/best'
  get 'live_casino/new'
  get 'live_casino/all'
  get 'live_casino/rules'

  get 'casino/best'
  get 'casino/new'
  get 'casino/all'
  get 'casino/rules'

  get 'sports/best'
  get 'sports/new'
  get 'sports/all'
  get 'sports/rules'

  get 'bingo/best'
  get 'bingo/new'
  get 'bingo/all'
  get 'bingo/rules'

  get 'slots', to: 'pages#slots'
  get 'live_casino', to: 'pages#live_casino'
  get 'casino', to: 'pages#casino'
  get 'sports', to: 'pages#sports'
  get 'bingo', to: 'pages#bingo'
  get 'best_offers', to: 'pages#best_offers'
  get 'articles', to: 'pages#articles'

  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/bingo_controller.rb
class BingoController < ApplicationController
  skip_before_action :authenticate_user!

  def best
  end
  def new
  end
  def all
  end
  def rules
  end
end

app/controllers/bingo_sites_controller.rb
class BingoSitesController < ApplicationController
  skip_before_action :authenticate_user!

  def sky_bingo
  end
  def bet365_bingo
  end
  def lippy_bingo
  end
  def glossy_bingo
  end
  def robin_hood_bingo
  end
  def coral_bingo
  end
  def ladbrokes_bingo
  end
  def sun_bingo
  end
  def bgo_bingo
  end
  def paddy_power_bingo
  end
end

app/controllers/casino_controller.rb
class CasinoController < ApplicationController
  skip_before_action :authenticate_user!

  def best
  end
  def new
  end
  def all
  end
  def rules
  end
end

app/controllers/casino_sites_controller.rb
class CasinoSitesController < ApplicationController
  skip_before_action :authenticate_user!

  def _888_casino
  end
  def mansion_casino
  end
  def royal_panda
  end
  def _32red
  end
  def grosvenor_casinos
  end
  def casumo
  end
  def leo_vegas
  end
  def betway_casino
  end
  def bet_victor
  end
  def netbet_casino
  end
end

app/controllers/corporate_controller.rb
class CorporateController < ApplicationController
  skip_before_action :authenticate_user!

  def about
  end
  def contact
  end
  def terms
  end
  def privacy
  end
  def responsible
  end
  def sitemap
  end
end

app/controllers/live_casino_controller.rb
class LiveCasinoController < ApplicationController
  skip_before_action :authenticate_user!

  def best
  end
  def new
  end
  def all
  end
  def rules
  end
end

app/controllers/live_casino_sites_controller.rb
class LiveCasinoSitesController < ApplicationController
  skip_before_action :authenticate_user!

  def _888_casino
  end
  def mansion_casino
  end
  def casumo
  end
  def netbet_casino
  end
  def royal_panda
  end
  def _32red
  end
  def bet_victor
  end
  def betway_casino
  end
  def grosvenor_casinos
  end
  def intercasino
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
  def slots
  end
  def live_casino
  end
  def casino
  end
  def sports
  end
  def bingo
  end
  def best_offers
  end
  def articles
  end

end

app/controllers/slot_sites_controller.rb
class SlotSitesController < ApplicationController
  skip_before_action :authenticate_user!

  def play_sunny
  end
  def spin_rider
  end
  def spinit
  end
  def sloty
  end
  def starspins
  end
  def videoslots
  end
  def casimba
  end
  def spin_and_win
  end
  def slot_planet
  end
  def casino_heroes
  end
end

app/controllers/slots_controller.rb
class SlotsController < ApplicationController
  skip_before_action :authenticate_user!

  def best
  end
  def new
  end
  def all
  end
  def rules
  end
end

app/controllers/sports_controller.rb
class SportsController < ApplicationController
  skip_before_action :authenticate_user!

  def best
  end
  def new
  end
  def all
  end
  def rules
  end
end

app/controllers/sports_sites_controller.rb
class SportsSitesController < ApplicationController
  skip_before_action :authenticate_user!

  def betway
  end
  def william_hill
  end
  def _888_sport
  end
  def pinnacle_sports
  end
  def unibet
  end
  def paddy_power
  end
  def betfred
  end
  def bet_victor
  end
  def ladbrokes
  end
  def tipico
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/casino/rules.html.erb
<!-- CSS found in _game.scss -->

<div class="game-nav">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "Best Casino Sites", casino_best_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "New Casino Sites", casino_new_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "All Casino Sites", casino_all_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "Casino Game Rules", casino_rules_path, class: "btn btn-game-nav" %>
      </div>
    </div>
  </div>
</div>

<div class="game-body game-body-casino">
  <div class="game-body-main">
    <div class="game-body-main-details">

      <h3 style="margin-top: 0;">How to play the most popular Casino games</h3>
      <p>Rules rules rules</p>
      <hr>

    </div>
  </div>

  <%= render 'shared/right_menu' %>
</div>

app/views/corporate/about.html.erb
<h1>Corporate#about</h1>
<p>Find me in app/views/corporate/about.html.erb</p>

app/views/corporate/contact.html.erb
<h1>Corporate#contact</h1>
<p>Find me in app/views/corporate/contact.html.erb</p>

app/views/corporate/privacy.html.erb
<h1>Corporate#privacy</h1>
<p>Find me in app/views/corporate/privacy.html.erb</p>

app/views/corporate/responsible.html.erb
<h1>Corporate#responsible</h1>
<p>Find me in app/views/corporate/responsible.html.erb</p>

app/views/corporate/terms.html.erb
<h1>Corporate#terms</h1>
<p>Find me in app/views/corporate/terms.html.erb</p>

app/views/shared/_footer.html.erb
<%= link_to "Articles", articles_path, class: "btn btn-articles" %>
<div class="footer-which">
  <div class="footer-content">
  <div class="container">

    <div class="row align-items-center">
      <%= link_to "About", corporate_about_path, class: "footer-links col-xs-12 col-md-offset-1 col-md-2" %>
      <%= link_to "Contact", corporate_contact_path, class: "footer-links col-xs-12 col-md-2" %>
      <%= link_to "Terms of Use", corporate_terms_path, class: "footer-links col-xs-12 col-md-2" %>
      <%= link_to "Privacy", corporate_privacy_path, class: "footer-links col-xs-12 col-md-2" %>
      <%= link_to "Gamble Responsibly", corporate_responsible_path, class: "footer-links col-xs-12 col-md-2" %>
    </div>
    <div class="row">
      <div class="disclaimer col-xs-12 col-md-6">
        <p>No part of this site, or the sites mentioned here, are intended for the use of persons under the age of 18. You must be over 18 to gamble.  All offers mentioned are subject to the terms and conditions of the individual sites and are not guaranteed by WhichCasinoGame. Online gambling is illegal in some jurisdictions. The reviews and opinions provided here are those of WhichCasinoGame and as such may reflect our own subjectivity.</p>
        <p>Please gamble responsibly.</p>
        <p>Copyright Which Casino Game 2018.</p>
      </div>
      <div class="footer-logo-div col-xs-12 col-md-6">
        <%= link_to root_path, class: "footer-logo" do %>
          <%= image_tag "chip.png", height: 150 %>
        <% end %>
      </div>
    </div>

  </div>
  </div>
</div>

app/views/slots/all.html.erb
<!-- CSS found in _game.scss -->

<div class="game-nav">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "Best Slots Sites", slots_best_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "New Slots Sites", slots_new_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "All Slots Sites", slots_all_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "How Slots Work", slots_rules_path, class: "btn btn-game-nav" %>
      </div>
    </div>
  </div>
</div>

<div class="game-body game-body-slots">
  <div class="game-body-main">
    <div class="game-body-main-details">

      <h3 style="margin-top: 0;">All the Slots sites you need to know about</h3>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <%= render 'shared/right_menu' %>
</div>


<%= link_to "play sunny", slot_sites_play_sunny_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "spin rider", slot_sites_spin_rider_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "spinit", slot_sites_spinit_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "sloty", slot_sites_sloty_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "starspins", slot_sites_starspins_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "videoslots", slot_sites_videoslots_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "casimba", slot_sites_casimba_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "spin and win", slot_sites_spin_and_win_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "slot planet", slot_sites_slot_planet_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "casino heroes", slot_sites_casino_heroes_path, class: "navbar-wagon-item navbar-wagon-link" %>

app/views/sports/all.html.erb
<!-- CSS found in _game.scss -->

<div class="game-nav">
  <div class="container">
    <div class="row">
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "Best Sports Betting Sites", sports_best_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "New Sports Betting Sites", sports_new_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "All Sports Betting Sites", sports_all_path, class: "btn btn-game-nav" %>
      </div>
      <div class="col-xs-12 col-sm-6 col-md-3">
        <%= link_to "Understand Sports Betting Odds", sports_rules_path, class: "btn btn-game-nav" %>
      </div>
    </div>
  </div>
</div>

<div class="game-body game-body-sports">
  <div class="game-body-main">
    <div class="game-body-main-details">

      <h3 style="margin-top: 0;">All the Sports betting sites you need to know about</h3>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>
      <hr>
      <div class="game-body-main-site">
        <div class="container">
          <div class="row" style="text-align: center;">
            <div class="col-xs-12 col-md-6">
              <%= link_to "https://www.skybingo.com", target: :_blank do %>
                <%= image_tag "bingo_sites/sky_bingo.jpg", class: "game-body-main-image" %>
              <% end %>
            </div>
            <div class="col-xs-12 col-md-6">
              <p>Sky Bingo - Spend £10 and play with £60</p>
            </div>
            <div class="col-xs-12">
              <%= link_to "Read More", bingo_sites_sky_bingo_path, class: "btn btn-read-more" %>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>

  <%= render 'shared/right_menu' %>
</div>


<%= link_to "betway", sports_sites_betway_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "william_hill", sports_sites_william_hill_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "888_sport", sports_sites__888_sport_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "pinnacle_sports", sports_sites_pinnacle_sports_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "unibet", sports_sites_unibet_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "paddy_power", sports_sites_paddy_power_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "betfred", sports_sites_betfred_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "bet_victor", sports_sites_bet_victor_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "ladbrokes", sports_sites_ladbrokes_path, class: "navbar-wagon-item navbar-wagon-link" %>
<%= link_to "tipico", sports_sites_tipico_path, class: "navbar-wagon-item navbar-wagon-link" %>